# Generated by Django 5.2.8 on 2025-11-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='exchange',
            field=models.CharField(default='global', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('symbol', 'exchange')},
        ),
    ]
