# Generated by Django 5.2.8 on 2025-11-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_asset_exchange_alter_asset_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
