# Generated by Django 5.2.8 on 2025-11-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_asset_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
